version: '3.8'

services:
  pocketbase:
    image: alpine:latest
    container_name: pocketbase-demo
    working_dir: /app
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase:/app/pocketbase:ro
      - ./pb_data:/app/pb_data
    command: /app/pocketbase serve --http=0.0.0.0:8090
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      # Optional: Configure via environment variables
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY:-}
    networks:
      - pocketbase-network

networks:
  pocketbase-network:
    driver: bridge

volumes:
  pb_data:
    driver: local

